DoesNotExist at /en/accounts/login/
No exception message supplied
Request Method:	GET
Request URL:	https://rent-management-62b874b791fb.herokuapp.com/en/accounts/login/
Django Version:	5.2.7
Exception Type:	DoesNotExist
Exception Location:	/app/.heroku/python/lib/python3.13/site-packages/allauth/socialaccount/adapter.py, line 302, in get_app
Raised during:	dashboard.views.CustomLoginView
Python Executable:	/app/.heroku/python/bin/python
Python Version:	3.13.7
Python Path:	
['/app/.heroku/python/bin',
 '/app',
 '/app/.heroku/python/lib/python313.zip',
 '/app/.heroku/python/lib/python3.13',
 '/app/.heroku/python/lib/python3.13/lib-dynload',
 '/app/.heroku/python/lib/python3.13/site-packages']
Server time:	Mon, 06 Oct 2025 18:55:46 +0400
Error during template rendering

In template /app/templates/registration/login.html, error at line 125
(Could not get exception message)
115	    <a href="#" class="social-btn w-1/2">
116	        <svg width="18" height="18" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
117	            <path d="M21 12.18c0-.63-.06-1.24-.18-1.82H12v3.44h5.4c-.23 1.24-.94 2.3-1.98 3.01v2.5h3.2C20.6 18.1 21 15.32 21 12.18z" fill="#4285F4"/>
118	            <path d="M12 22c2.7 0 4.97-.9 6.63-2.45l-3.2-2.5c-.9.6-2.05.96-3.43.96-2.63 0-4.85-1.77-5.64-4.16H2.98v2.6C4.63 19.9 8.04 22 12 22z" fill="#34A853"/>
119	            <path d="M6.36 13.85A6.99 6.99 0 016 12c0-.65.1-1.28.28-1.85V7.55H2.98A10.98 10.98 0 002 12c0 1.78.43 3.46 1.2 4.95l2.16-3.1z" fill="#FBBC05"/>
120	            <path d="M12 6.5c1.47 0 2.79.5 3.83 1.48l2.87-2.87C16.95 3.5 14.7 2.5 12 2.5 8.04 2.5 4.63 4.6 2.98 7.55l3.3 2.6C7.15 8.27 9.37 6.5 12 6.5z" fill="#EA4335"/>
121	        </svg>
122	        <span class="text-xs">{% trans "تسجيل بـ Google" %}</span>
123	    </a>
124	
125	    <a href="{% provider_login_url 'github' %}" class="social-btn w-1/2">
126	        <svg width="18" height="18" viewBox="0 0 24 24" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
127	            <path d="M12 .5C5.65.5.5 5.66.5 12.02c0 5.09 3.29 9.4 7.86 10.93.58.11.79-.25.79-.56 0-.28-.01-1.02-.02-2-3.2.7-3.88-1.38-3.88-1.38-.53-1.35-1.3-1.71-1.3-1.71-1.06-.72.08-.71.08-.71 1.17.08 1.78 1.2 1.78 1.2 1.04 1.78 2.72 1.27 3.38.97.11-.76.41-1.27.75-1.56-2.56-.29-5.26-1.28-5.26-5.7 0-1.26.45-2.28 1.2-3.08-.12-.3-.52-1.52.11-3.17 0 0 .98-.31 3.2 1.18a11.1 11.1 0 012.92-.39c.99.01 1.99.13 2.92.39 2.22-1.5 3.2-1.18 3.2-1.18.63 1.65.23 2.87.11 3.17.75.8 1.2 1.82 1.2 3.08 0 4.43-2.7 5.41-5.27 5.69.42.36.8 1.07.8 2.16 0 1.56-.01 2.82-.01 3.2 0 .31.21.68.8.56A11.53 11.53 0 0023.5 12C23.5 5.66 18.35.5 12 .5z"/>
128	        </svg>
129	        <span class="text-xs">{% trans "تسجيل بـ GitHub" %}</span>
130	    </a>
131	</div>
132	
133	            <button type="submit" class="w-full bg-[#993333] text-white py-3 px-4 rounded-lg font-medium hover:bg-[#7c2a2a] transition-colors text-base md:text-lg">{% trans "دخول" %}</button>
134	        </form>
135	    </div>
Traceback Switch to copy-and-paste view

/app/.heroku/python/lib/python3.13/site-packages/django/core/handlers/exception.py, line 55, in inner
                response = get_response(request)
                               ^^^^^^^^^^^^^^^^^^^^^ …
Local vars
/app/.heroku/python/lib/python3.13/site-packages/django/core/handlers/base.py, line 220, in _get_response
                response = response.render()
                                ^^^^^^^^^^^^^^^^^ …
Local vars
/app/.heroku/python/lib/python3.13/site-packages/django/template/response.py, line 114, in render
            self.content = self.rendered_content
                                ^^^^^^^^^^^^^^^^^^^^^ …
Local vars
/app/.heroku/python/lib/python3.13/site-packages/django/template/response.py, line 92, in rendered_content
        return template.render(context, self._request)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ …
Local vars
/app/.heroku/python/lib/python3.13/site-packages/django/template/backends/django.py, line 107, in render
            return self.template.render(context)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ …
Local vars
/app/.heroku/python/lib/python3.13/site-packages/django/template/base.py, line 171, in render
                    return self._render(context)
                                ^^^^^^^^^^^^^^^^^^^^^ …
Local vars
/app/.heroku/python/lib/python3.13/site-packages/django/template/base.py, line 163, in _render
        return self.nodelist.render(context)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ …
Local vars
/app/.heroku/python/lib/python3.13/site-packages/django/template/base.py, line 1016, in render
        return SafeString("".join([node.render_annotated(context) for node in self]))
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ …
Local vars
/app/.heroku/python/lib/python3.13/site-packages/django/template/base.py, line 977, in render_annotated
            return self.render(context)
                        ^^^^^^^^^^^^^^^^^^^^ …
Local vars
/app/.heroku/python/lib/python3.13/site-packages/django/template/library.py, line 321, in render
        output = self.func(*resolved_args, **resolved_kwargs)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ …
Local vars
/app/.heroku/python/lib/python3.13/site-packages/allauth/socialaccount/templatetags/socialaccount.py, line 21, in provider_login_url
        provider = adapter.get_provider(request, provider)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ …
Local vars
/app/.heroku/python/lib/python3.13/site-packages/allauth/socialaccount/adapter.py, line 212, in get_provider
            app = self.get_app(request, provider=provider, client_id=client_id)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ …
Local vars
/app/.heroku/python/lib/python3.13/site-packages/allauth/socialaccount/adapter.py, line 302, in get_app
            raise SocialApp.DoesNotExist()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ …
Local vars
Request information

USER
AnonymousUser
GET
No GET data
POST
No POST data
FILES
No FILES data
COOKIES
Variable	Value
csrftoken	
'********************'
django_language	
'en'
META
Variable	Value
CSRF_COOKIE	
'CmyzJZjgiKZZ3oXpOJpjwRqjETrdX5i6'
CSRF_COOKIE_NEEDS_UPDATE	
True
HTTP_ACCEPT	
'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8'
HTTP_ACCEPT_ENCODING	
'gzip, deflate, br'
HTTP_ACCEPT_LANGUAGE	
'ar'
HTTP_COOKIE	
'********************'
HTTP_HOST	
'rent-management-62b874b791fb.herokuapp.com'
HTTP_SEC_FETCH_DEST	
'document'
HTTP_SEC_FETCH_MODE	
'navigate'
HTTP_SEC_FETCH_SITE	
'none'
HTTP_SERVER	
'Heroku'
HTTP_USER_AGENT	
('Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, '
 'like Gecko) Version/17.6 Safari/605.1.15')
HTTP_VIA	
'1.1 heroku-router'
HTTP_X_FORWARDED_FOR	
'141.105.173.162'
HTTP_X_FORWARDED_PORT	
'443'
HTTP_X_FORWARDED_PROTO	
'https'
HTTP_X_REQUEST_ID	
'd83e6a54-fc5d-a897-b8de-8c2f55efbe7a'
HTTP_X_REQUEST_START	
'1759762546016'
PATH_INFO	
'/en/accounts/login/'
QUERY_STRING	
''
RAW_URI	
'/en/accounts/login/'
REMOTE_ADDR	
'10.1.40.188'
REMOTE_PORT	
'59680'
REQUEST_METHOD	
'GET'
SCRIPT_NAME	
''
SERVER_NAME	
'0.0.0.0'
SERVER_PORT	
'5620'
SERVER_PROTOCOL	
'HTTP/1.1'
SERVER_SOFTWARE	
'gunicorn/23.0.0'
gunicorn.socket	
<socket.socket fd=10, family=2, type=1, proto=0, laddr=('172.16.175.130', 5620), raddr=('10.1.40.188', 59680)>
wsgi.errors	
<gunicorn.http.wsgi.WSGIErrorsWrapper object at 0x7f4f91570ac0>
wsgi.file_wrapper	
<class 'gunicorn.http.wsgi.FileWrapper'>
wsgi.input	
<gunicorn.http.body.Body object at 0x7f4f91568650>
wsgi.input_terminated	
True
wsgi.multiprocess	
True
wsgi.multithread	
False
wsgi.run_once	
False
wsgi.url_scheme	
'https'
wsgi.version	
(1, 0)
Settings
Using settings module rent_management.settings

Setting	Value
ABSOLUTE_URL_OVERRIDES	
{}
ACCOUNT_AUTHENTICATION_METHOD	
'********************'
ACCOUNT_EMAIL_REQUIRED	
True
ACCOUNT_EMAIL_VERIFICATION	
'optional'
ADMINS	
[]
ALLOWED_HOSTS	
['*']
APPEND_SLASH	
True
AUTHENTICATION_BACKENDS	
'********************'
AUTH_PASSWORD_VALIDATORS	
'********************'
AUTH_USER_MODEL	
'********************'
BASE_DIR	
PosixPath('/app')
CACHES	
{'default': {'BACKEND': 'django.core.cache.backends.locmem.LocMemCache'}}
CACHE_MIDDLEWARE_ALIAS	
'default'
CACHE_MIDDLEWARE_KEY_PREFIX	
'********************'
CACHE_MIDDLEWARE_SECONDS	
600
CSRF_COOKIE_AGE	
31449600
CSRF_COOKIE_DOMAIN	
None
CSRF_COOKIE_HTTPONLY	
False
CSRF_COOKIE_NAME	
'csrftoken'
CSRF_COOKIE_PATH	
'/'
CSRF_COOKIE_SAMESITE	
'Lax'
CSRF_COOKIE_SECURE	
False
CSRF_FAILURE_VIEW	
'django.views.csrf.csrf_failure'
CSRF_HEADER_NAME	
'HTTP_X_CSRFTOKEN'
CSRF_TRUSTED_ORIGINS	
[]
CSRF_USE_SESSIONS	
False
DATABASES	
{'default': {'ATOMIC_REQUESTS': False,
             'AUTOCOMMIT': True,
             'CONN_HEALTH_CHECKS': False,
             'CONN_MAX_AGE': 0,
             'ENGINE': 'django.db.backends.mysql',
             'HOST': 'fojvtycq53b2f2kx.chr7pe7iynqr.eu-west-1.rds.amazonaws.com',
             'NAME': 'ox3h62lb0h2hwudt',
             'OPTIONS': {},
             'PASSWORD': '********************',
             'PORT': '3306',
             'TEST': {'CHARSET': None,
                      'COLLATION': None,
                      'MIGRATE': True,
                      'MIRROR': None,
                      'NAME': None},
             'TIME_ZONE': None,
             'USER': 'oilpoycpc2s9fv9d'}}
DATABASE_ROUTERS	
[]
DATA_UPLOAD_MAX_MEMORY_SIZE	
2621440
DATA_UPLOAD_MAX_NUMBER_FIELDS	
1000
DATA_UPLOAD_MAX_NUMBER_FILES	
100
DATETIME_FORMAT	
'N j, Y, P'
DATETIME_INPUT_FORMATS	
['%Y-%m-%d %H:%M:%S',
 '%Y-%m-%d %H:%M:%S.%f',
 '%Y-%m-%d %H:%M',
 '%m/%d/%Y %H:%M:%S',
 '%m/%d/%Y %H:%M:%S.%f',
 '%m/%d/%Y %H:%M',
 '%m/%d/%y %H:%M:%S',
 '%m/%d/%y %H:%M:%S.%f',
 '%m/%d/%y %H:%M']
DATE_FORMAT	
'N j, Y'
DATE_INPUT_FORMATS	
['%Y-%m-%d',
 '%m/%d/%Y',
 '%m/%d/%y',
 '%b %d %Y',
 '%b %d, %Y',
 '%d %b %Y',
 '%d %b, %Y',
 '%B %d %Y',
 '%B %d, %Y',
 '%d %B %Y',
 '%d %B, %Y']
DEBUG	
True
DEBUG_PROPAGATE_EXCEPTIONS	
False
DECIMAL_SEPARATOR	
'.'
DEFAULT_AUTO_FIELD	
'django.db.models.BigAutoField'
DEFAULT_CHARSET	
'utf-8'
DEFAULT_EXCEPTION_REPORTER	
'django.views.debug.ExceptionReporter'
DEFAULT_EXCEPTION_REPORTER_FILTER	
'django.views.debug.SafeExceptionReporterFilter'
DEFAULT_FROM_EMAIL	
'webmaster@localhost'
DEFAULT_INDEX_TABLESPACE	
''
DEFAULT_TABLESPACE	
''
DISALLOWED_USER_AGENTS	
[]
EMAIL_BACKEND	
'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST	
'localhost'
EMAIL_HOST_PASSWORD	
'********************'
EMAIL_HOST_USER	
''
EMAIL_PORT	
25
EMAIL_SSL_CERTFILE	
None
EMAIL_SSL_KEYFILE	
'********************'
EMAIL_SUBJECT_PREFIX	
'[Django] '
EMAIL_TIMEOUT	
None
EMAIL_USE_LOCALTIME	
False
EMAIL_USE_SSL	
False
EMAIL_USE_TLS	
False
FILE_UPLOAD_DIRECTORY_PERMISSIONS	
None
FILE_UPLOAD_HANDLERS	
['django.core.files.uploadhandler.MemoryFileUploadHandler',
 'django.core.files.uploadhandler.TemporaryFileUploadHandler']
FILE_UPLOAD_MAX_MEMORY_SIZE	
2621440
FILE_UPLOAD_PERMISSIONS	
420
FILE_UPLOAD_TEMP_DIR	
None
FIRST_DAY_OF_WEEK	
0
FIXTURE_DIRS	
[]
FORCE_SCRIPT_NAME	
None
FORMAT_MODULE_PATH	
None
FORMS_URLFIELD_ASSUME_HTTPS	
False
FORM_RENDERER	
'django.forms.renderers.DjangoTemplates'
IGNORABLE_404_URLS	
[]
INSTALLED_APPS	
['modeltranslation',
 'django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django.contrib.sites',
 'dashboard',
 'portal',
 'allauth',
 'allauth.account',
 'allauth.socialaccount',
 'allauth.socialaccount.providers.google',
 'allauth.socialaccount.providers.github']
INTERNAL_IPS	
[]
LANGUAGES	
[('ar', 'Arabic'), ('en', 'English')]
LANGUAGES_BIDI	
['he', 'ar', 'ar-dz', 'ckb', 'fa', 'ug', 'ur']
LANGUAGE_CODE	
'ar'
LANGUAGE_COOKIE_AGE	
None
LANGUAGE_COOKIE_DOMAIN	
None
LANGUAGE_COOKIE_HTTPONLY	
False
LANGUAGE_COOKIE_NAME	
'django_language'
LANGUAGE_COOKIE_PATH	
'/'
LANGUAGE_COOKIE_SAMESITE	
None
LANGUAGE_COOKIE_SECURE	
False
LOCALE_PATHS	
['/app/locale']
LOGGING	
{}
LOGGING_CONFIG	
'logging.config.dictConfig'
LOGIN_REDIRECT_URL	
'/'
LOGIN_URL	
'/accounts/login/'
LOGOUT_REDIRECT_URL	
'/accounts/login/'
MANAGERS	
[]
MEDIA_ROOT	
'/app/media'
MEDIA_URL	
'/media/'
MESSAGE_STORAGE	
'django.contrib.messages.storage.fallback.FallbackStorage'
MIDDLEWARE	
['django.middleware.security.SecurityMiddleware',
 'whitenoise.middleware.WhiteNoiseMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.locale.LocaleMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'allauth.account.middleware.AccountMiddleware']
MIGRATION_MODULES	
{}
MONTH_DAY_FORMAT	
'F j'
NUMBER_GROUPING	
0
PASSWORD_HASHERS	
'********************'
PASSWORD_RESET_TIMEOUT	
'********************'
PREPEND_WWW	
False
ROOT_URLCONF	
'rent_management.urls'
SECRET_KEY	
'********************'
SECRET_KEY_FALLBACKS	
'********************'
SECURE_CONTENT_TYPE_NOSNIFF	
True
SECURE_CROSS_ORIGIN_OPENER_POLICY	
'same-origin'
SECURE_HSTS_INCLUDE_SUBDOMAINS	
False
SECURE_HSTS_PRELOAD	
False
SECURE_HSTS_SECONDS	
0
SECURE_PROXY_SSL_HEADER	
None
SECURE_REDIRECT_EXEMPT	
[]
SECURE_REFERRER_POLICY	
'same-origin'
SECURE_SSL_HOST	
None
SECURE_SSL_REDIRECT	
False
SERVER_EMAIL	
'root@localhost'
SESSION_CACHE_ALIAS	
'default'
SESSION_COOKIE_AGE	
1209600
SESSION_COOKIE_DOMAIN	
None
SESSION_COOKIE_HTTPONLY	
True
SESSION_COOKIE_NAME	
'sessionid'
SESSION_COOKIE_PATH	
'/'
SESSION_COOKIE_SAMESITE	
'Lax'
SESSION_COOKIE_SECURE	
False
SESSION_ENGINE	
'django.contrib.sessions.backends.db'
SESSION_EXPIRE_AT_BROWSER_CLOSE	
False
SESSION_FILE_PATH	
None
SESSION_SAVE_EVERY_REQUEST	
False
SESSION_SERIALIZER	
'django.contrib.sessions.serializers.JSONSerializer'
SETTINGS_MODULE	
'rent_management.settings'
SHORT_DATETIME_FORMAT	
'm/d/Y P'
SHORT_DATE_FORMAT	
'm/d/Y'
SIGNING_BACKEND	
'django.core.signing.TimestampSigner'
SILENCED_SYSTEM_CHECKS	
[]
SITE_ID	
1
SOCIALACCOUNT_PROVIDERS	
{'github': {'SCOPE': ['user', 'repo', 'read:org']},
 'google': {'AUTH_PARAMS': '********************',
            'SCOPE': ['profile', 'email']}}
STATICFILES_DIRS	
['/app/static']
STATICFILES_FINDERS	
['django.contrib.staticfiles.finders.FileSystemFinder',
 'django.contrib.staticfiles.finders.AppDirectoriesFinder']
STATICFILES_STORAGE	
'whitenoise.storage.CompressedManifestStaticFilesStorage'
STATIC_ROOT	
'/app/staticfiles'
STATIC_URL	
'/static/'
STORAGES	
{'default': {'BACKEND': 'django.core.files.storage.FileSystemStorage'},
 'staticfiles': {'BACKEND': 'django.contrib.staticfiles.storage.StaticFilesStorage'}}
TEMPLATES	
[{'APP_DIRS': True,
  'BACKEND': 'django.template.backends.django.DjangoTemplates',
  'DIRS': ['/app/templates'],
  'OPTIONS': {'context_processors': ['django.template.context_processors.debug',
                                     'django.template.context_processors.request',
                                     'django.contrib.auth.context_processors.auth',
                                     'django.contrib.messages.context_processors.messages',
                                     'django.template.context_processors.i18n',
                                     'django.template.context_processors.request'],
              'libraries': {'dashboard_extras': 'dashboard.templatetags.dashboard_extras'}}}]
TEST_NON_SERIALIZED_APPS	
[]
TEST_RUNNER	
'django.test.runner.DiscoverRunner'
THOUSAND_SEPARATOR	
','
TIME_FORMAT	
'P'
TIME_INPUT_FORMATS	
['%H:%M:%S', '%H:%M:%S.%f', '%H:%M']
TIME_ZONE	
'Asia/Muscat'
USE_I18N	
True
USE_L10N	
True
USE_THOUSAND_SEPARATOR	
False
USE_TZ	
True
USE_X_FORWARDED_HOST	
False
USE_X_FORWARDED_PORT	
False
WSGI_APPLICATION	
'rent_management.wsgi.application'
X_FRAME_OPTIONS	
'DENY'
YEAR_MONTH_FORMAT	
'F Y'
You’re seeing this error because you have DEBUG = True in your Django settings file. Change that to False, and Django will display a standard page generated by the handler for this status code.